name: cn_workday_calendar
description: China mainland legal holiday, adjusted workday, and workday calendar for Dart.
version: 0.1.0
repository: https://github.com/kevinyu1666/cn_workday_calendar

environment:
  sdk: ^3.11.0

executables:
  cn_workday_calendar:

dependencies:

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
